name: Token Count (by repository/ref)

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: "owner/repo, e.g. someorg/somerepo"
        required: true
        type: string
      target_ref:
        description: "Branch, tag, or commit SHA (default: main)"
        required: false
        default: "main"
        type: string
      model:
        description: "Tokenizer model (use OpenAI model to avoid API calls)"
        required: false
        default: "o3"
        type: string

jobs:
  count-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this workflow repo (contains the script)
        uses: actions/checkout@v4

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target_repo }}
          ref: ${{ inputs.target_ref }}
          # For private repos, add a PAT secret with scope contents:read
#          token: ${{ secrets.REPO_READ_TOKEN }} # omit this line for public repos
          path: target

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (from this repo)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run token counter on the target repo (plain text)
        run: |
          python count_tokens.py target --model "${{ inputs.model }}" --pretty-output false > token_summary.txt

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: token-summary
          path: token_summary.txt

      - name: Set job summary
        if: always()
        run: |
          echo "## Token Count Summary" >> $GITHUB_STEP_SUMMARY
          echo "Repository: ${{ inputs.target_repo }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref: ${{ inputs.target_ref }}" >> $GITHUB_STEP_SUMMARY
          echo "Model: ${{ inputs.model }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand raw output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat token_summary.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
